project:
  type: website
  output-dir: docs

website:
  title: "lindsay.codes"
  site-url: "https://lindsay.codes"
  description: "Lindsay Lee's techy blog"
  favicon: "favicon.png"
  draft-mode: unlinked
  navbar:
    background: "#eee8d5"
    right:
      - about.qmd
      - icon: link
        href: https://lindsayevanslee.com
      - icon: linkedin
        href: https://linkedin.com/in/lindsayevanslee
      - icon: github
        href: https://github.com/lindsayevanslee
      # - icon: bluesky
      #   href: https://bsky.app/profile/lindsay.codes

format:
  html:
    theme: 
      - solar
      - custom.scss
    header-includes: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
    mainfont: Roboto Mono
    code-block-bg: "#eee8d5"

resources:
  - CNAME

editor: visual

# Include both posts and drafts directories
posts:
  - posts/
  - drafts/

